Vagrant.configure("2") do |config|

  config.vm.box = "aestasit/devops-ubuntu-16.04"
  config.vm.box_check_update = false

  # IF HyperV:

    # NO PRIVATE NETWORK: config.vm.network "private_network", ip: "192.168.23.10"

    # Extra options for syncing folders
    syncedFolderOpts = { 
      type: "smb", 
      mount_options: [
        "vers=3.02",
        "sec=ntlmssp", 
        "iocharset=utf8", 
        "mapchars", 
        "noperm", 
        "soft"
      ]
    }

    config.vm.synced_folder ".", "/vagrant", syncedFolderOpts

  # END IF HyperV

end
