Vagrant.configure("2") do |config|

  config.vm.box = "aestasit/devops-ubuntu-16.04"
  config.vm.box_check_update = false

  # IF HyperV:

    # NO PRIVATE NETWORK: config.vm.network "private_network", ip: "192.168.23.10"

    # Extra options for syncing folders
    syncedFolderOpts = { 
      type: "smb", 
      mount_options: [
        "vers=3.02",
        "sec=ntlmssp", 
        "iocharset=utf8", 
        "mapchars", 
        "noperm", 
        "soft"
      ]
    }

    config.vm.synced_folder ".", "/vagrant", syncedFolderOpts

    config.vm.provider "hyperv" do |h|
      h.vmname = 'test-box' 
      h.vm_integration_services = {
        guest_service_interface: true,
        heartbeat: true,
        key_value_pair_exchange: true,
        shutdown: true,
        time_synchronization: true,
        vss: true
      }
    end

  # END IF HyperV

end
